### ISSUE TITLE
MVP: prototype run of training, prediction and issue creating on new code

### ISSUE THREAD

**Issue by goern** [AICoE/Varangian#14]
**Is your feature request related to a problem? Please describe.**
As a Product Owner, I want to see a manual demo of the monolith, so that new issues are created based on new code comits of one specific repository.

**High-level Goals**
- [ ] show interaction between model and bot
- [ ] new issues on new code
- [ ] automated issue creation

**Describe the solution you'd like**
TBA

**Describe alternatives you've considered**
TBA

**Additional context**
TBA

**Acceptance Criteria**
TBA

**Comment by KPostOffice** [comment]
Hey @sahilsuneja1 is this something we could demo?
