### ISSUE TITLE
Generate Cross dataset baselines for models

### ISSUE THREAD

**Issue by saurabhpujar** [AICoE/Varangian#30]
Baselines are for small models and C-BERT

Results: https://ibm.ent.box.com/file/870740616272

**Comment by saurabhpujar** [comment]
ML Models baseline analysis:

Scenarios:
1. Large projects (Large: 100k < # training samples)
	- Can train and test on project data itself
	- Focus on def-sec issues, full dataset can be overwhelming for the models 
	- Good results for OpenSSL, Libav (Exp: 1, 2)
	- Model can be trained on combined data (Exp: 3)
	- Cross dataset results for project and combined models are bad (Exp: 1, 2, 3)

2. Medium projects (Medium: 10k < # training samples)
	- Model can train on project data itself
	- def-sec subset is too small to train models
	- Good results for Libtiff, Httpd, Nginx (Exp: 5, 6, 7)
	- Models can be trained on combined data (Exp: 4)
	- Combined model gives good results on combined test set for def-sec (Exp: 4)
	- Project trained models give reasonable results for combined def-sec test set (Exp: 5, 6, 7)
	- Cross dataset results for project models are bad (Exp: 5, 6, 7)

3. Small projects (Small: 1.5k < # training samples)
	- Model can train on project data itself (Exp: 46, 47, 49, 50, 52, 53, 55, 56, 58, 59)
	- Adding small projects to large or medium projects is not helpful.

4. Very small projects (V Small: 1.5k > #training samples)
	- Model cannot train on project data
	- Adding very small projects to large or medium projects is not helpful.
	- **Needs cross dataset training to be useful.**

**Comment by lucaburatti7** [comment]
C-BERT analysis: 

1. same conclusions as ML models 
2. same conclusions as ML models 
3. similar conclusions as ML models (OpenSSL and libtiff are a little bit worse). In general there is a decreasing trend going from small to smallest as expected: C-BERT benefits having large amount of data.
4. same as ML models
