### ISSUE TITLE
Finalize System Architecture: Online Mode

### ISSUE THREAD

**Issue by saurabhpujar** [AICoE/Varangian#8]
First draft of the online mode. Basically what exists today. 

<img width="1179" alt="Screen Shot 2021-04-26 at 7 43 15 AM" src="https://user-images.githubusercontent.com/5577724/116077119-1937ea00-a663-11eb-913a-04ec7f97dd16.png">

**Comment by saurabhpujar** [comment]
Copying Burn's analysis for Dataflow:

<img width="1060" alt="Screen Shot 2021-04-26 at 7 53 52 AM" src="https://user-images.githubusercontent.com/5577724/116078439-9a43b100-a664-11eb-8f3d-5e08373a1479.png">

**Comment by burn2l** [comment]
Inference pipeline for ML models delivered to https://github.com/rh-ibm-synergy/fp_reduction on August 27th.  Inclusion of BERT results not yet done.
