### ISSUE TITLE
Finalize System Architecture: Offline Mode

### ISSUE THREAD

**Issue by saurabhpujar** [AICoE/Varangian#9]
First draft of the offline model training mode. Basically what exists today.

<img width="1204" alt="Screen Shot 2021-04-26 at 7 46 01 AM" src="https://user-images.githubusercontent.com/5577724/116077536-982d2280-a663-11eb-9d09-60a67890da06.png">

**Comment by saurabhpujar** [comment]
Copying Burn's analysis for Dataflow:

<img width="1088" alt="Screen Shot 2021-04-26 at 7 52 48 AM" src="https://user-images.githubusercontent.com/5577724/116078293-6a94a900-a664-11eb-91aa-c5f5b11b9cbc.png">

**Comment by goern** [comment]
@saurabhpujar all steps up until we have a fine-tuned models saved to disk, is what we want to deploy as a (pretty) continuous pipeline on Open Data Hub/Operate First, right?

@erikerlandson I think some parts of this will involve Ray, could you help with that?

Our primary key result for this issue should be:
- [ ] Design document for Model Training Pipeline
- [ ] Implementation Plan (set of follow up issues)

**Comment by saurabhpujar** [comment]
@goern Sorry I didn't realize you had messaged since this Github account is connected to my college email which I don't check very often. 😄 

In the offline mode yes that is correct. In the Online Inference mode #8 there are some changes in the data pre-processing and we will have to deploy the inference part as well.
